spring: 
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
    web-application-type: servlet
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

logging:
  level:
    org.hibernate.SQL: error

custom:
  auth:
    validation: true